name: Test custom action
on:
  push:
jobs:
  test-hello-world-custom-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: 'World'
      - name: Greet output time
        run: |
          echo "Time: ${{steps.hello.outputs.time}}"
